# Generated by Django 5.1.6 on 2025-03-03 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='renters_who_messaged',
            field=models.ManyToManyField(blank=True, related_name='messaged_flats', to=settings.AUTH_USER_MODEL),
        ),
    ]
