# Generated by Django 5.1.6 on 2025-03-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0002_flat_renters_who_messaged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
