# Generated by Django 5.1.6 on 2025-03-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_alter_flat_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
