# Generated by Django 5.1.6 on 2025-03-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0004_flat_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='available',
        ),
    ]
