# Generated by Django 5.2.3 on 2025-09-14 14:49

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0005_remove_flat_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='bath',
            new_name='washroom',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='description_4',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='description_5',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='feature_1',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='feature_2',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='feature_3',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='feature_4',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='feature_5',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='flat_size',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='price',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='room',
        ),
        migrations.AddField(
            model_name='flat',
            name='cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='commode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='floor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='flat',
            name='garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='image_5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='flat',
            name='roof_top_uses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='tiles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='water_supply',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='kitchen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Bachelor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_seats', models.CharField(max_length=50)),
                ('dininig_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_rate_range', models.CharField(max_length=100)),
                ('extra_cost_range', models.CharField(max_length=100)),
                ('expected_total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_members', models.CharField(max_length=50)),
                ('khala_facility', models.BooleanField(default=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bachelor_details', to='flat.flat')),
            ],
            options={
                'verbose_name': 'Bachelor Flat',
                'verbose_name_plural': 'Bachelor Flats',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_room', models.IntegerField()),
                ('dining_room', models.BooleanField(default=True)),
                ('drawing_room', models.BooleanField(default=True)),
                ('balcony', models.BooleanField(default=False)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_details', to='flat.flat')),
            ],
            options={
                'verbose_name': 'Family Flat',
                'verbose_name_plural': 'Family Flats',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('square_feet', models.IntegerField()),
                ('preaching_space', models.BooleanField(default=True)),
                ('address', models.TextField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_details', to='flat.flat')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
    ]
