# Generated by Django 5.2.3 on 2025-09-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0006_rename_bath_flat_washroom_remove_flat_description_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_flats', to='flat.location'),
        ),
    ]
