# Generated by Django 5.2.3 on 2025-09-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0007_alter_flat_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bachelor',
            old_name='dininig_charge',
            new_name='dining_charge',
        ),
    ]
