# Generated by Django 5.1.6 on 2025-03-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='house_holding_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
